#数据库驱动mysql
spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:mysql://localhost:3306/blogs?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://185.245.1.134:3306/blogs?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#日志打印
logging:
  level:
    root: info
    com.yrp: debug
  file: log/blog-dev.log
server:
  port: 3030